/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Kotlin application project to get you started.
 * For more details take a look at the 'Building Java & JVM projects' chapter in the Gradle
 * User Manual available at https://docs.gradle.org/7.3/userguide/building_java_projects.html
 */
// this is removed doe to it is in the top level build.gradle
/*plugins {
    // Apply the org.jetbrains.kotlin.jvm Plugin to add support for Kotlin.
    /*id("org.jetbrains.kotlin.jvm") version "1.5.31"*/

    // Apply the application plugin to add support for building a CLI application in Java.
    //application
}*/



